### ISSUE TITLE
怎么编译armeabi的包

### ISSUE THREAD

**Issue by penghao1** [yu12mang/Android-Native-Unzip#1]
以前为了减小apk体积，只保留了armeabi的so。这个怎么更改能编译armeabi架构的so呢？

**Comment by yu12mang** [comment]
修改build.gradle中的ndk代码块：
ndk { 
      abiFilters 'armeabi' 
   }

**Comment by penghao1** [comment]
昨晚试了的，报错，说只有armeabi-v7a，arm64，x86等四个可以。就是没有armeabi。

**Comment by penghao1** [comment]
下面是报错信息：
`ABIs [armeabi] are not supported for platform. Supported ABIs are [armeabi-v7a, arm64-v8a, x86, x86_64].`

**Comment by yu12mang** [comment]
Ndk16以上不支持armeabi用13或者14版本试试




| |
18126226779
邮箱：18126226779@163.com
|

Signature is customized by Netease Mail Master

在2019年05月07日 12:29，penghao1 写道：

下面是报错信息：
ABIs [armeabi] are not supported for platform. Supported ABIs are [armeabi-v7a, arm64-v8a, x86, x86_64].

**Comment by penghao1** [comment]
好的，谢谢。
